# Ray Tune configuration
ray:
  num_samples: 4
  resources_per_trial:
    gpu: 1

# choose metric which will be optimized by Ray Tune
optimized_metric: "val/zero/in/hospital/auc/dataloader_idx_1"
direction: "max"

# Define the search space
search_space:
  model.optimizer.lr:
    _target_: ray.tune.loguniform
    lower: 1e-4
    upper: 1e-2
  model.backbone.dropout:
    _target_: ray.tune.uniform
    lower: 0.0
    upper: 0.3

scheduler:
  _target_: ray.tune.schedulers.ASHAScheduler
  max_t: ${trainer.max_epochs}
  grace_period: 2
  reduction_factor: 2

# Choose between train and finetune
train_fn: ${name}
