
_target_: meds_torch.models.zero_shot_labeler.TaskLabeler

target_codes: ???
time_length: ???
min_time: 0.0
numeric_value_min: null
numeric_value_max: null
include_min_time: True
include_max_time: True
