BACKBONE_EMBEDDINGS_KEY = "BACKBONE//EMBEDDINGS"
BACKBONE_TOKENS_KEY = "BACKBONE//TOKENS"


MODEL_EMBEDDINGS_KEY = "MODEL//EMBEDDINGS"
MODEL_TOKENS_KEY = "MODEL//TOKENS"
MODEL_LOSS_KEY = "MODEL//LOSS"
MODEL_LOGITS_KEY = "MODEL//LOGITS"
