_target_: meds_torch.input_encoder.triplet_encoder.TripletEncoder.initialize
collate_style: triplet
_resolved_max_seq_len: ${model._resolved_max_seq_len}
token_dim: ${model.token_dim}
vocab_size: ${data.dataset.vocab_size}
