defaults:
  - input_encoder: histogram_encoder
  - backbone: histogram_transformer_decoder
  - trajectory_labeler: null
  - optimizer: adam
  - scheduler: null
  - _self_
_target_: meds_torch.models.histogram_forecasting.HistogramForecastingModule.initialize

max_seq_len: ${data.max_seq_len}
token_dim: 4
vocab_size: ${data.augmented_vocab_size}
subvocab_size: ${data.subvocab_size}
get_representations: false
task_name: ${data.task_name}
batch_size: ${data.dataloader.batch_size}
code_head:
  _target_: torch.nn.Identity
augmented_code_metadata_fp: ${data.augmented_code_metadata_fp}

# compile model for faster training with pytorch 2.0
compile: false

# sampling parameters
generate_id: null # null means no sampling, otherwise uses this id to generate the trajectory
store_generated_trajectory: true # whether to store generated trajectory in the batch
# set to false to speed up zero-shot generation
temperature: 1.0 # sampling temperature
eos_tokens:
  - ${data.EOS_TOKEN_ID}
log_progress: true

# Autoregressive modeling metric params
top_k_acc:
  - 1
  - 5
  - 10
next_token_auc: false
max_tokens_budget: null
return_logits: false
return_tokens: false
return_labeler: false
prune_terminated: true

# TODO(Oufattole) add autoencoder embed_dim that is smaller than token_dim
token_insertion_strategy: ${data.token_insertion_strategy}
token_bin_size: ${data.token_bin_size}
n_bits: 8
max_count: 8
scale: 1.0
histogram_batch_mul: 1
beta: 1e-3
histogram_loss_weight: 1
histogram_head_loss: 'l2' # bce, l2, or l1
use_diffusion: false
diffusion_noise_schedule: linear
warmup_steps: 0
annealing_steps: 0
deterministic: false

use_linear_encoder: true
encoder_dims: [768, 768, 768, 768]
decoder_dims: [768, 768, 768, 768]
autoencoder_type: "vae"
autoencoder_mi_num_layers: 3
autoencoder_mi_mask_prob: 0.8
autoencoder_mi_num_iters: 1
