_target_: meds_torch.input_encoder.triplet_encoder.TripletEncoder.initialize
collate_style: triplet
max_seq_len: ${sequence_model.max_seq_len}
token_dim: ${sequence_model.token_dim}
vocab_size: ${sequence_model.vocab_size}
