predicates:
  hospital_admission:
    code: {regex: "HOSPITAL_ADMISSION//.*"}
  lab:
    code: "LAB//50912//mg/dL"
  high_lab:
    code: "LAB//50912//mg/dL"
    value_min: 2.0
    value_min_inclusive: True
  abnormal_lab:
    expr: or(high_lab, low_lab)

trigger: hospital_admission

windows:
  input:
    start: NULL
    end: trigger
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
  target:
    start: input.end
    end: start + 2m
    start_inclusive: False
    end_inclusive: True
    has:
      lab: (1, None)
    label: abnormal_lab
