#This config checks for an abnormal platets lab within 30d after HOSPITAL_DISCHARGE
predicates:
  trigger_event:
    code: {regex: "HOSPITAL_DISCHARGE//.*"}
  lab:
    code: {regex: "LAB//51265//K/uL"}
  abnormal_lab:
    code: {regex: "LAB//51265//K/uL"}
    value_max: 20
    value_max_inclusive: True


trigger: trigger_event

windows:
  input:
    start: NULL
    end: trigger
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
  target:
    start: input.end
    end: start + 30d
    start_inclusive: True
    end_inclusive: True
    has:
      lab: (1, None)
    label: abnormal_lab
