#This config checks for an abnormal platets lab within 30d after ICU_DISCHARGE
predicates:
  trigger_event:
    code: {regex: "ICU_DISCHARGE//.*"}

  lab:
    code: {regex: LAB//51265//K/uL}

  lab_0:
    code: "LAB//51265//K/uL"
    value_max: 20
    value_max_inclusive: True

  abnormal_lab:
    expr: or(lab_0)


trigger: trigger_event

windows:
  input:
    start: NULL
    end: trigger
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
  target:
    start: input.end
    end: start + 30d
    start_inclusive: False
    end_inclusive: True
    has:
      lab: (1, None)
    label: abnormal_lab
