#This config checks for an abnormal hemoglobin lab within 90d after HOSPITAL_DISCHARGE
predicates:
  trigger_event:
    code: {regex: "HOSPITAL_DISCHARGE//.*"}
  lab:
    code: {regex: "LAB//51645//g/dL|LAB//51222//g/dL|LAB//50811//g/dL|LAB//50855//UNK"}
  abnormal_lab:
    code: {regex: "LAB//51645//g/dL|LAB//51222//g/dL|LAB//50811//g/dL|LAB//50855//UNK"}
    value_min: 2.0
    value_min_inclusive: True


trigger: trigger_event

windows:
  input:
    start: NULL
    end: trigger
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
  target:
    start: input.end
    end: start + 90d
    start_inclusive: True
    end_inclusive: True
    has:
      lab: (1, None)
    label: abnormal_lab
