#This config checks for an abnormal hematocrit lab within 90d after HOSPITAL_DISCHARGE
predicates:
  trigger_event:
    code: {regex: "HOSPITAL_DISCHARGE//.*"}

  lab:
    code: {regex: LAB//51221//%|LAB//51638//%|LAB//50810//%}

  lab_0:
    code: "LAB//51221//%"
    value_max: 24
    value_max_inclusive: True

  lab_1:
    code: "LAB//51638//%"
    value_max: 24
    value_max_inclusive: True

  lab_2:
    code: "LAB//50810//%"
    value_max: 24
    value_max_inclusive: True

  abnormal_lab:
    expr: or(lab_0,lab_1,lab_2)


trigger: trigger_event

windows:
  input:
    start: NULL
    end: trigger
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
  target:
    start: input.end
    end: start + 90d
    start_inclusive: False
    end_inclusive: True
    has:
      lab: (1, None)
    label: abnormal_lab
